version: '3.2'
services:
  cc:
    container_name: cocalc_pytorch
    user: root
    command: python /root/run.py
    ports:
      - 443:443
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ~/cocalc:/projects
#      - /etc/timezone:/etc/timezone
#      - /etc/localtime:/etc/localtime
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
#    environment:
#      - COCALC_NO_IDLE_TIMEOUT=yes